import type { Job } from "@/types/jobs";

export const MOCK_JOBS: Job[] = [
  {
    id: "job-1",
    title: "Senior Frontend Engineer",
    company: "Anthropic",
    location: "San Francisco, CA",
    remote: true,
    salary: { min: 5500000, max: 8000000, currency: "INR" },
    description:
      "Build the next generation of AI interfaces. Work on Claude's consumer and enterprise products using React, TypeScript, and modern web technologies.",
    requirements: [
      "5+ years of frontend experience",
      "Expert in React and TypeScript",
      "Experience with AI/ML products",
      "Strong system design skills",
      "Experience with real-time streaming UIs",
    ],
    source: "LinkedIn",
    sourceUrl: "https://linkedin.com/jobs/view/123",
    postedDate: new Date(Date.now() - 86400000 * 2).toISOString(),
    matchScore: 92,
    matchReasons: [
      "Perfect role match: Senior Frontend Engineer",
      "5/5 core skills matched (React, TypeScript, Next.js)",
      "AI domain alignment",
      "Remote-friendly",
    ],
    saved: false,
    dismissed: false,
  },
  {
    id: "job-2",
    title: "Frontend Engineer, AI Products",
    company: "Vercel",
    location: "Remote",
    remote: true,
    salary: { min: 4500000, max: 7000000, currency: "INR" },
    description:
      "Join Vercel's AI team to build developer tools and AI-powered features. Work on v0, AI SDK, and Next.js integrations.",
    requirements: [
      "4+ years frontend development",
      "Deep Next.js and React expertise",
      "TypeScript proficiency",
      "Experience with AI SDKs or LLM integrations",
      "Open source contributions a plus",
    ],
    source: "Wellfound",
    sourceUrl: "https://wellfound.com/jobs/123",
    postedDate: new Date(Date.now() - 86400000 * 1).toISOString(),
    matchScore: 88,
    matchReasons: [
      "Strong role match: Frontend Engineer",
      "Next.js expertise is core requirement",
      "AI SDK experience directly relevant",
      "Fully remote",
    ],
    saved: false,
    dismissed: false,
  },
  {
    id: "job-3",
    title: "Senior Software Engineer - Frontend",
    company: "Notion",
    location: "Bengaluru, India",
    remote: false,
    salary: { min: 4000000, max: 6500000, currency: "INR" },
    description:
      "Build Notion's AI features and collaborative editing experience. Work on rich text editors, real-time sync, and AI-powered writing tools.",
    requirements: [
      "5+ years software engineering",
      "Strong React and TypeScript skills",
      "Experience with rich text editors",
      "Performance optimization expertise",
      "Interest in AI/ML applications",
    ],
    source: "LinkedIn",
    sourceUrl: "https://linkedin.com/jobs/view/456",
    postedDate: new Date(Date.now() - 86400000 * 3).toISOString(),
    matchScore: 85,
    matchReasons: [
      "Senior Frontend role match",
      "React + TypeScript core skills match",
      "Bengaluru location match",
      "AI product focus",
    ],
    saved: false,
    dismissed: false,
  },
  {
    id: "job-4",
    title: "Staff Frontend Engineer",
    company: "Razorpay",
    location: "Bengaluru, India",
    remote: false,
    salary: { min: 4500000, max: 7500000, currency: "INR" },
    description:
      "Lead frontend architecture for Razorpay's payment dashboard and merchant tools. Drive technical decisions and mentor the frontend team.",
    requirements: [
      "7+ years frontend experience",
      "Expert in React ecosystem",
      "Experience leading frontend teams",
      "Fintech domain knowledge preferred",
      "Strong system design and architecture skills",
    ],
    source: "Indeed",
    sourceUrl: "https://indeed.com/jobs/view/789",
    postedDate: new Date(Date.now() - 86400000 * 5).toISOString(),
    matchScore: 72,
    matchReasons: [
      "Frontend engineer role match",
      "React expertise matches",
      "Bengaluru location",
      "Fintech domain — partial match",
    ],
    saved: false,
    dismissed: false,
  },
  {
    id: "job-5",
    title: "Frontend Developer - AI Platform",
    company: "Hugging Face",
    location: "Remote (Global)",
    remote: true,
    salary: { min: 5000000, max: 8500000, currency: "INR" },
    description:
      "Build the web interfaces for Hugging Face's model hub, Spaces, and inference APIs. Create delightful developer experiences for the ML community.",
    requirements: [
      "4+ years frontend development",
      "React and TypeScript proficiency",
      "Experience building developer tools",
      "Familiarity with ML/AI concepts",
      "Open source mindset",
    ],
    source: "RemoteOK",
    sourceUrl: "https://remoteok.com/jobs/123",
    postedDate: new Date(Date.now() - 86400000 * 1).toISOString(),
    matchScore: 90,
    matchReasons: [
      "Frontend developer role match",
      "React + TypeScript match",
      "AI/ML domain — strong alignment",
      "Fully remote",
      "Developer tools experience valued",
    ],
    saved: false,
    dismissed: false,
  },
  {
    id: "job-6",
    title: "Senior Frontend Engineer",
    company: "Postman",
    location: "Bengaluru, India",
    remote: true,
    salary: { min: 3500000, max: 5500000, currency: "INR" },
    description:
      "Build and improve Postman's web client and API platform tools. Work on complex UI challenges like API design, testing flows, and collaboration features.",
    requirements: [
      "5+ years frontend experience",
      "Strong React and JavaScript skills",
      "Experience with complex web applications",
      "API design knowledge a plus",
      "Performance optimization skills",
    ],
    source: "LinkedIn",
    sourceUrl: "https://linkedin.com/jobs/view/101",
    postedDate: new Date(Date.now() - 86400000 * 4).toISOString(),
    matchScore: 76,
    matchReasons: [
      "Senior Frontend role match",
      "React skills match",
      "Developer tools — good domain fit",
      "Bengaluru + remote hybrid",
    ],
    saved: false,
    dismissed: false,
  },
  {
    id: "job-7",
    title: "Frontend Engineer - Growth",
    company: "Zepto",
    location: "Mumbai, India",
    remote: false,
    salary: { min: 3000000, max: 4500000, currency: "INR" },
    description:
      "Drive frontend development for Zepto's growth initiatives. Build landing pages, checkout flows, and A/B testing frameworks.",
    requirements: [
      "3+ years frontend development",
      "React and Next.js experience",
      "A/B testing and analytics experience",
      "Performance optimization",
      "Mobile-first development",
    ],
    source: "Indeed",
    sourceUrl: "https://indeed.com/jobs/view/202",
    postedDate: new Date(Date.now() - 86400000 * 6).toISOString(),
    matchScore: 58,
    matchReasons: [
      "Frontend role match",
      "React + Next.js skills match",
      "Not AI domain",
      "Below target salary range",
    ],
    saved: false,
    dismissed: false,
  },
  {
    id: "job-8",
    title: "Lead Frontend Engineer",
    company: "Stability AI",
    location: "Remote",
    remote: true,
    salary: { min: 6000000, max: 9000000, currency: "INR" },
    description:
      "Lead the frontend team building Stability AI's creative tools and API playground. Design and implement interfaces for image/video generation models.",
    requirements: [
      "6+ years frontend experience",
      "React, TypeScript, and modern CSS",
      "Experience leading small teams",
      "Interest in generative AI",
      "Canvas/WebGL experience a plus",
    ],
    source: "Wellfound",
    sourceUrl: "https://wellfound.com/jobs/456",
    postedDate: new Date(Date.now() - 86400000 * 2).toISOString(),
    matchScore: 82,
    matchReasons: [
      "Lead Frontend — stretch but achievable",
      "React + TypeScript match",
      "AI domain — strong alignment",
      "Remote + above salary target",
    ],
    saved: false,
    dismissed: false,
  },
];
